schema_version = "1.0.0"

id = "polychase"
version = "0.0.6"
name = "Polychase"
tagline = "Mesh Based Motion Tracking in Blender"
maintainer = "Ahmed Essam"
type = "add-on"
website = "https://github.com/theartful/polychase"
tags = ["Animation", "Tracking"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
platforms = ["windows-x64", "linux-x64"]
wheels = [
    "./wheels/polychase_core-0.0.2-cp311-cp311-manylinux_2_28_x86_64.whl",
    "./wheels/polychase_core-0.0.2-cp311-cp311-win_amd64.whl"
]

[permissions]
files = "Write optical flow database to disk"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
  "lib/",
]
